name: Mirror to Ebrains

on:
  push:
    branches: [ main ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: syncmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "ngeorgomanolis/nkg"
          source_branch: "main"
          destination_repo: "https://nkgpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/ngeorgomanolis/nkg"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "ngeorgomanolis/nkg"
          source_branch: "refs/tags/*"
          destination_repo: "https://nkgpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/ngeorgomanolis/nkg"
          destination_branch: "refs/tags/*"
